sudo: required

language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
# command to install dependencies
services:
  - docker
install:
  - pip install -r requirements.txt scipy codecov
# command to run tests
script:
  - py.test --cov=gsmodutils -p no:warnings
after_success:
  - codecov